### ISSUE TITLE
Firefox57 greasemonkey error:"GM_getValue is not defined"

### ISSUE THREAD

**Issue by ufo5260987423** [liqi0816/bilitwin#1]
Script error:  
ReferenceError
columnNumber: 9
fileName: "resource://gre/modules/ExtensionContent.jsm"
lineNumber: 396
**message: "GM_getValue is not defined"**
stack: "userScript/<@user-script:http%3A//tampermonkey.net//%u7834%u89E3VIP%u5728%u7EBF%u89C6%u9891:396:9\nuserScript@user-script:http%3A//tampermonkey.net//%u7834%u89E3VIP%u5728%u7EBF%u89C6%u9891:394:2\nscopeWrapper@user-script:http%3A//tampermonkey.net//%u7834%u89E3VIP%u5728%u7EBF%u89C6%u9891:534:9\n@user-script:http%3A//tampermonkey.net//%u7834%u89E3VIP%u5728%u7EBF%u89C6%u9891:361:17\n"

**Comment by liqi0816** [comment]
This script does not require GM_getValue since version 1.5. Are you using the latest version?
