### ISSUE TITLE
idm导出是可以用idm下载吗，那么这个导出的文件要怎么用呀（调用idm打开这个文件也没反应）

### ISSUE THREAD

**Issue by HIMQ** [liqi0816/bilitwin#10]
设置里的“自动全屏”是“自动网页全屏”能不能改成全屏啊

**Comment by liqi0816** [comment]
1. http://www.internetdownloadmanager.cn/idm/25128
2. - 这是全屏而不是网页全屏，因为控制栏会自动隐藏，也没有弹幕栏
   - 如果浏览器认为用户可能不知情，就会拒绝直接全屏。需要按F11告知浏览器“朕知道了”

**Comment by HIMQ** [comment]
感谢回复(=・ω・=)
1.涨姿势了，idm刚用几个月不知道这么操作
2.试了下f11，确实能全屏。但这是每次都要按一次f11呀，能不能做成全自动的
还有就是那个跳oped的功能不是很懂，是每个视频都要去标记？

在 2018-01-24 12:32:19，"qli5" <notifications@github.com> 写道：

http://www.internetdownloadmanager.cn/idm/25128
这是全屏而不是网页全屏，因为控制栏会自动隐藏，也没有弹幕栏
如果浏览器认为用户可能不知情，就会拒绝直接全屏。需要按F11告知浏览器“朕知道了”

**Comment by liqi0816** [comment]
2. 无解，如果有的话算浏览器bug，除非做成扩展程序
3. 支持同av不同p，和同番剧号不同ep
    `(top.location.pathname.match(/av\d+/) || top.location.hash.match(/av\d+/) || top.document.querySelector('div.bangumi-info a').href).toString()`

**Comment by HIMQ** [comment]
这样啊，多谢了

在 2018-01-25 11:07:28，"qli5" <notifications@github.com> 写道：

无解，如果有的话算浏览器bug，除非做成扩展程序
支持同av不同p，和同番剧号不同ep
(top.location.pathname.match(/av\d+/) || top.location.hash.match(/av\d+/) || top.document.querySelector('div.bangumi-info a').href).toString()

**Comment by HIMQ** [comment]
这个跳oped的还是用不来，比如某个番op是01：04开始，02：35结束，但标记片头01：04，视频就直接跳到01：04了
能教教具体的操作方法吗

在 2018-01-25 11:07:28，"qli5" <notifications@github.com> 写道：

无解，如果有的话算浏览器bug，除非做成扩展程序
支持同av不同p，和同番剧号不同ep
(top.location.pathname.match(/av\d+/) || top.location.hash.match(/av\d+/) || top.document.querySelector('div.bangumi-info a').href).toString()

**Comment by liqi0816** [comment]
这个功能参照的是其它播放器。一般的本地播放器跳片头是直接跳，土豆优酷也是，所以设计的时候也是直接跳。

不过一些番剧在最前面和最后面加了一些东西，确实可以考虑标记四个时间点，然后到中间再跳。看心情加。
> 快了~

**Comment by HIMQ** [comment]
这两天出现一些视频里脚本失效的情况。越来越多了举个栗子地址https://www.bilibili.com/video/av19018681/

**Comment by liqi0816** [comment]
多谢阁下反馈。脚本已经更新。

如果问题继续存在，请告诉我。

**Comment by HIMQ** [comment]
用脚本下的ass弹幕文件跟用jj下的不一样唉。脚本的字体比较粗，jj下的跟B站的比较相似。这是怎么回事有没有办法弄成偏向B站原来那样的字体？（左边的是用jj下的弹幕文件，右边是脚本）



在 2018-02-02 13:14:03，"qli5" <notifications@github.com> 写道：


多谢阁下反馈。脚本已经更新。

如果问题继续存在，请告诉我。

**Comment by liqi0816** [comment]
已经增加了四个时间点的标记功能，和弹幕字体的设置功能。欢迎阁下试试开发版本：https://github.com/liqi0816/bilitwin/raw/develop/biliTwin.user.js

如果可用，将在两天后释出。
