### ISSUE TITLE
打开弹幕过滤会导致下载到的弹幕 ass 文件无内容

### ISSUE THREAD

**Issue by Seaward233** [liqi0816/bilitwin#13]
设置里打开 "弹幕过滤：在网页播放器里设置的屏蔽词也对下载的弹幕生效" 功能时下载到的ass文件仅有样式,没有弹幕内容

**Comment by liqi0816** [comment]
弹幕屏蔽列表是怎样的？

**Comment by Seaward233** [comment]
感谢您的回复,我现在无法复现问题了. 就当做无事发生吧ˋ( ° ▽、° )
