### ISSUE TITLE
部分 ass 下载按钮无法使用

### ISSUE THREAD

**Issue by Seaward233** [liqi0816/bilitwin#14]
这两个点击都显示未发现文件
![2018-01-30 1 _li](https://user-images.githubusercontent.com/35931149/35527567-208ce4fa-0566-11e8-8480-7af010e815e3.jpg)

这个能正常使用
![2018-01-30 2 _li](https://user-images.githubusercontent.com/35931149/35527610-4c2c72a6-0566-11e8-99d7-a7475996ff0c.jpg)

**Comment by Seaward233** [comment]
![2018-01-30 4](https://user-images.githubusercontent.com/35931149/35563826-fa55ba54-05f2-11e8-8537-3a5aecbf3bee.png)

**Comment by liqi0816** [comment]
多谢阁下反馈。注意到，如果用户不登录，B站的追踪脚本就会往奇怪的地方放参数，ass地址因此被修改：

> blob:https://www.bilibili.com/5cb75681-03bc-423d-a0b6-7f94ac2ff69f
> 变成
> blob:https://www.bilibili.com/5cb75681-03bc-423d-a0b6-7f94ac2ff69f?log=.view.balabala

欢迎阁下试试修正版本
https://github.com/liqi0816/bilitwin/raw/develop/biliTwin.user.js

如果可用，将在明天释出。
