### ISSUE TITLE
某些视频里工具条错位

### ISSUE THREAD

**Issue by ferristale** [liqi0816/bilitwin#17]
估计是跟vip在线解析冲突了
https://greasyfork.org/zh-CN/scripts/30659-%E7%A0%B4%E8%A7%A3%E5%85%A8%E7%BD%91vip%E8%A7%86%E9%A2%91%E4%BC%9A%E5%91%98-%E5%8E%BB%E5%B9%BF%E5%91%8A

----
实例：
https://www.bilibili.com/video/av18997782/?t=255

![image](https://user-images.githubusercontent.com/18678403/36306773-43758de0-1354-11e8-91d7-3259823d285d.png)

**Comment by liqi0816** [comment]
多谢阁下反馈。已经改善了与该脚本的兼容性。欢迎阁下试试开发版本
https://github.com/liqi0816/bilitwin/raw/develop/biliTwin.user.js

如果可用，将随下次更新释出。

**Comment by ferristale** [comment]
谢谢，试了几个网页，表现正常！
