### ISSUE TITLE
请问缓存地址是哪里

### ISSUE THREAD

**Issue by ferristale** [liqi0816/bilitwin#18]
我把chrome缓存地址改到另外一个盘，缓存的时候是在我修改后的位置？

**Comment by ferristale** [comment]
看到有个可用缓存空间，这是作者定义的吗？不会和浏览器本身设置冲突？

**Comment by liqi0816** [comment]
1. 是在修改后的位置。
2. 是浏览器分配给每个网站的。只不过除了webgl游戏，很少有网站会真的用这么多。如果B站自己打算做缓存了，也是用的这个空间。
  https://developer.chrome.com/apps/offline_storage
