### ISSUE TITLE
番剧设置界面不可用/自动抓取/自动合并

### ISSUE THREAD

**Issue by ferristale** [liqi0816/bilitwin#19]
1. 设置的入口是不是在播放器右键呢，但是那里没有可以改动的项目
2. 自动抓取不知道是什么意思？打开视频页面就能自动缓存吗，确实有网络请求但是似乎没有保存下来
3. 能不能实现看完之后，flv也下载完毕，直接就可以合并呢？没有手动点击缓存分段的情况下

**Comment by liqi0816** [comment]
1. 右键菜单完全没有东西，还是无法弹出设置界面？请留下浏览器版本和测试页面，以便跟进。
2. 自动进行“正在xxx”的阶段。
3. > 懒得加的功能：
> * 边看边下载  
>   一旦进度条鬼畜，下载就会拉肚子。

**Comment by ferristale** [comment]
<img width="479" alt="_20180219104222" src="https://user-images.githubusercontent.com/18678403/36360804-08dd0964-1562-11e8-9b7d-7e36cf57a090.png">
我指的是这里的界面，没有可以动的选项


浏览器版本：
![image](https://user-images.githubusercontent.com/18678403/36360850-5c83c4e0-1562-11e8-9e50-542635d4e01f.png)

**Comment by liqi0816** [comment]
以[centbrowser_3.2.4.23_x64_portable](http://static.centbrowser.com/installer_64/centbrowser_3.2.4.23_x64_portable.exe)测试，脚本可以正常显示设置界面。是不是还用了其他插件/脚本/样式？

**Comment by ferristale** [comment]
你好，投稿视频正常显示，请测试一下[番剧](https://www.bilibili.com/bangumi/play/ep173292)
附所有插件
![image](https://user-images.githubusercontent.com/18678403/36929823-39c93ac0-1ed1-11e8-98f8-8f383f05f25a.png)

**Comment by liqi0816** [comment]
多谢阁下反馈。B站的css简直匪夷所思
```css
* {
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
}
```
>稍有常识的人都会看出，"*"是多危险的东西

已经修正了css。欢迎阁下试试开发版本
https://github.com/liqi0816/bilitwin/raw/develop/biliTwin.user.js

如果可用，将在两天后释出。

**Comment by ferristale** [comment]
测试了几部番，均表现正常。感谢！
