### ISSUE TITLE
问下 GM 如何实现弹出一个新建的窗口来进行内容操作

### ISSUE THREAD

**Issue by pendave** [liqi0816/bilitwin#2]
问下 GM 如何实现 点击页面里自己添加的按钮 

会弹出一个新建的窗口 里面有自己要copy出来的文本

因为有的网站限制了按钮的响应 我想在新的窗口里来操作内容

bilibili merged flv+mp4+ass+enhance

这个脚本就是实现了一个新弹出窗口来操作下载、合并等

https://greasyfork.org/zh-CN/scripts/27819-bilibili-merged-flv-mp4-ass-enhance 

但我想移植出来这种窗口自己用，不知是哪个函数？或者有样例吗？

**Comment by liqi0816** [comment]
弹出下载的代码位于`UI.genDiv()`。示例：

```javascript
const div = UI.genDiv();
div.innerHTML = 'foo';
document.body.appendChild(div);
button.onclick = () => div.style.display = '';
```

`UI.genFLVDiv()` `UI.genOptionDiv()` `UI.displayPolyfillDataDiv()`都用了这个函数。

> 因为有的网站限制了按钮的响应 我想在新的窗口里来操作内容

不是很清楚“按钮”是指页面上的按钮，还是鼠标右键。如果是鼠标右键，这个生成的div仍然在文档的范围内，所以也会受到限制。解决：
* 直接复制到剪贴板
  ```javascript
  UI.copyToClipboard(text)
  ```
* 新开窗口
  ```javascript
  const child = top.open('', undefined, ' ');
  child.document.write('foo');
  ```

**Comment by pendave** [comment]
Thanks
我说的限制了按钮复制我要的文本内容的站是
// @match        https://y.qq.com/portal/player.html
我用的复制到剪贴板的第三方是
// @require  https://cdn.jsdelivr.net/clipboard.js/1.5.13/clipboard.min.js
目前的问题是我无法复制出我要的文本，应该是网站有限制手段，以前是可以操作的。

![41tyg3ijx ub4 go f3 n_t](https://user-images.githubusercontent.com/1331881/34138217-7132b41c-e4a9-11e7-83b8-f4c40c939f51.png)

**Comment by liqi0816** [comment]
> clipboard能触发copy的操作，但是实际上结果剪贴板里无内容

clipboard.js这些库的目标是支持各种IE，不是破解限制。所以无内容很正常。

分析一下网页，很明显就是这两个eventlistener在捣乱：
![listener](https://user-images.githubusercontent.com/20200613/34139865-1705794e-e4b2-11e7-8aa2-4d3dcfe8d271.JPG)

方法有三种：
* 防止它们绑定到网页 
  [greasyfork: 网页限制解除](https://greasyfork.org/zh-CN/scripts/14146)
* 删掉它们
  F12，然后去点remove
* 绕过它们
  直觉上，可以跳出当前这个document
  ```javascript
  function copyToClipboardStealthily(text) {
    // create a new context
    const iframe = document.createElement('iframe');
    
    // must be visible to execute command
    document.body.appendChild(iframe);
    
    // get the brand new context
    const contentDocument = iframe.contentDocument;
    
    // free!
    const textarea = contentDocument.createElement('textarea');
    contentDocument.body.appendChild(textarea);
    textarea.value = text;
    textarea.select();
    contentDocument.execCommand('copy');
    
    // clean
    document.body.removeChild(iframe);
  }
  ```
