### ISSUE TITLE
ASS 弹幕里有一个 Timer 标签似乎造成播放器兼容问题

### ISSUE THREAD

**Issue by gonejack** [liqi0816/bilitwin#22]
ASS 弹幕里有一个 Timer 标签似乎造成播放器兼容问题

```
Timer: 10.0000
```

在一个网页版ASS播放器里导致慢了10倍，https://github.com/weizhenye/ASS/issues/6#issuecomment-368198773

**Comment by liqi0816** [comment]
多谢阁下反馈。已经嵌入了新版ASS转换插件。欢迎阁下试试开发版本
https://github.com/liqi0816/bilitwin/raw/develop/biliTwin.user.js

如果可用，将在两天后释出。

**Comment by gonejack** [comment]
没什么问题，默认的字体间隔有些小，但这属于个人爱好问题。
