### ISSUE TITLE
tx cdn速度很慢，可以脚本强制锁定upos？

### ISSUE THREAD

**Issue by 1265578519** [liqi0816/bilitwin#23]
tx cdn速度很慢，可以脚本强制锁定upos？

**Comment by liqi0816** [comment]
已经增加了cdn-preference功能。欢迎阁下试试cdn-preference分支：https://github.com/liqi0816/bilitwin/raw/cdn-preference/biliTwin.user.js

这项功能应该比较小众，而且也不知道B站分配CDN的策略，所以并*不*一定会加到正式版中，除非有显著效果。

**Comment by 1265578519** [comment]
![qq 20180228201443](https://user-images.githubusercontent.com/6442439/36787204-3e9624fa-1cc4-11e8-87a6-968a1bef7c55.png)
嗯，，没效果，好像也无法二次呼出这个框。

**Comment by liqi0816** [comment]
* 暂时只改了解析出来的下载地址。是想要换掉播放器的地址吗？
* 因为还不知道好不好使，所以没做什么UI。重置脚本设置就可以再次呼出。
