### ISSUE TITLE
Doesn't work with Edge browser

### ISSUE THREAD

**Issue by Vast-Stars** [liqi0816/bilitwin#25]
Environment: 
Microsoft Edge 41.16299.15.0
Microsoft EdgeHTML 16.16299

Problem:
The page doesn't show anything new. It seems this script does not work at all.

**Comment by liqi0816** [comment]
1. Try the Babel transpiled version <https://liqi0816.github.io/bilitwin/biliTwinBabelCompiled.user.js>
2. Edge support is *never* guaranteed or on track. The *smart* Windows Update keeps replacing my hardware drivers and causes a BSoD every week, so perhaps I must stick with Windows 7 for now.
