### ISSUE TITLE
为什么番剧是复制下载链接，而投稿是导出idm

### ISSUE THREAD

**Issue by ayanamist** [liqi0816/bilitwin#27]
我发现代码里`genFLVDiv`函数中，如果不是bangumi，则会将已有的“复制下载链接”替换成“到处idm”？这个设计的原因是？

我个人使用aria2，所以更喜欢复制下载链接，每次脚本升级的时候都要手动改一下，毕竟都只是个referrer校验

**Comment by liqi0816** [comment]
因为在上古时代的时候，番剧还不会检测referrer，所以怎么方便怎么来。

但是现在好像番剧也要了，正在考虑怎么办。加上导出aria？

**Comment by ayanamist** [comment]
我个人使用是不用导出aria的，我自己的改法是始终提供“复制链接”因为我不用idm而且有包装好的aria框架只要贴url进去就好了。
如果说统一ui风格的话，把复制链接和idm导出都提供出来如何？

**Comment by liqi0816** [comment]
多谢阁下反馈。现在提供了新的选项，可以导出aria.session、发送JSON RPC或者复制全部链接。欢迎阁下试试开发版本
https://github.com/liqi0816/bilitwin/raw/develop/biliTwin.user.js

如果可用，将在两天后释出。

**Comment by ayanamist** [comment]
我按自己的需求，自己做了一个

https://greasyfork.org/scripts/40141-bilibili-video-urls
