### ISSUE TITLE
[诚征大佬建议]怎样解耦这个项目？

### ISSUE THREAD

**Issue by liqi0816** [liqi0816/bilitwin#36]
> 啊……毕竟图样图森破，还是要学习一个才行。

这应该是我第一个代码量上万的项目。所以，菜鸡常见的问题出现了——现在的代码像意大利面一样乱糟糟，没法维护。急需大佬指点：怎样解耦这个项目，让它变得更优雅？

需要组织起来的组件有

- `BiliMonkey`，需要不换P，否则需要destroy
- `BiliPolyfill`，需要不换P+不换清晰度，换清晰度需要videoRefresh，换P需要destroy
- `UI`，需要不换P+不换清晰度，换清晰度需要videoRefresh，换P需要cidRefresh

作为插件，最大的问题就是**并非所有状态都可控**。

- 如果只需要cli，程序其实很简单，**因为可以假设源站点的状态不变**，对于B站来说，就是可以假设不换P，不换清晰度，等等
- 如果需要gui，瞬间爆炸~
  换P、换清晰度之后，后台的`BiliMonkey`、`BiliPolyfill`，前台的`UI`都需要做出反应，而且需要互相同步。但是，监测换P/换清晰度靠的是`addEventListener`，监听器之间没有原生的数据通道。所以，后台需要知道前台的流程，前台也需要知道后台，全耦合在一起。

最明显的后果就是交叉引用，呵呵……

```javascript
this.ui = ui || new UI(this); 
```

想要啥

- 漂亮~~妹子~~程序！
- 不新加第三方库，B站自带的除外
- ESNext可以接受
- Experimental Web Platform Features可以接受

**Comment by gonejack** [comment]
做成 Chrome 娘插件（雾

**Comment by liqi0816** [comment]
实在拖不下去了，终于写了`OnEventDuplexFactory`，这回应该可以顺畅地写代码了。[README.md](https://github.com/liqi0816/bilitwin/blob/12b4c43002775b81f1b4d3be727fe8a9a13e0294/README.md)

**Comment by changhexiong** [comment]
2.0-nightly这个版本现在可以用了吗？
辛苦了^_^

**Comment by MrZQAQ** [comment]
最后还是自己造了个轮子23333

**Comment by orangle** [comment]
加个油干。。
