### ISSUE TITLE
部分视频无限小电视

### ISSUE THREAD

**Issue by 86xiang** [liqi0816/bilitwin#42]
### 哪一个页面？
https://www.bilibili.com/video/av26692488
https://www.bilibili.com/video/av26692410
https://www.bilibili.com/video/av26646590
https://www.bilibili.com/video/av26645429

### 出了什么问题？
无限小电视

### 用的浏览器是？
QQ浏览器

**Comment by Xmader** [comment]
我帮作者更新了一下脚本，应该可以使用了
Github地址: https://github.com/Xmader/bilitwin
Greasy Fork地址: https://greasyfork.org/scripts/372516
