### ISSUE TITLE
番剧网址被重定向，脚本失效了

### ISSUE THREAD

**Issue by MaxMadcc** [liqi0816/bilitwin#5]
以前是番剧是bangumi.bilibili.com/anime/*/play*
现在重定向到了www.bilibili.com/bangumi/play*
能解决下问题吗？

**Comment by IsoaSFlus** [comment]
+1 ,昨天还能用，今天就不行了。。。

**Comment by liqi0816** [comment]
多谢诸位反馈。已经跟进B站更新。欢迎阁下试试修正版本：https://github.com/liqi0816/bilitwin/raw/develop/biliTwin.user.js

如果可用，将在两天后释出。

**Comment by IsoaSFlus** [comment]
@liqi0816  可用

**Comment by MaxMadcc** [comment]
可用，暂时没发现有问题
