### ISSUE TITLE
ｂ站又双叒叕出现HTTP 403问题了

### ISSUE THREAD

**Issue by knightReigh** [liqi0816/bilitwin#6]
看隔壁ｙｏｕ-ｇｅｔ那边的[解决方法](https://github.com/soimort/you-get/pull/2555)是加一个ｈｅａｄｅｒ信息。　(〃▽〃)

话说代码分析出来的视频地址就是: `http://interface.bilibili.com/playurl?cid=29763633&from=miniplay&player=1&sign=ba28cbb150ffbeb18d4949e21824cbb6`了吗？

有可能分析出可以直接下载的.mp4/.flv地址啊？我想加一个只下载声音的功能，据说用ffmpeg就行。但估计ffmpeg不能解析`interface`这样的链接.

**Comment by liqi0816** [comment]
多谢阁下反馈。

脚本直接插入页面，调用B站原生方法，因此理所当然地有完整的header：除了Referer和User-Agent，Cookie乃至于Accept-Language都会带上。但是，脚本只能控制当前标签页。所以，在实践中

- 可以
  - 左键单击
  - 右键目标另存为
  - 右键新标签页打开
  - 右键调用IDM*
  - 右键调用迅雷*
- 不可以
  - 右键新隐身窗口打开
  - 复制到地址栏打开
  - 复制到IDM下载
  - 其他跳出当前标签页的下载方式

\* 如果正确安装

如果确实会报403，烦请提供问题页面，以便跟进。

------

很明显，形如`//interface.*/*?`这样的地址提供的是API，而不是内容。实际上，`//interface.bilibili.com/playurl?`响应的是一个JSON，其中包含了视频地址。如果给出正确的header，其中的地址就是可以直接下载的。这也是脚本的工作原理：监听当前标签页的网络连接，拦截这个地址上的响应，提取出地址，放入用户界面。

即使指定只保留音频，ffmpeg也不能跳过视频数据，只能在下载到视频数据后丢弃，这是HTTP不能seek决定的。所以，我推荐完整下载mp4之后，再用ffmpeg转码。

*实际上，脚本也引用了flv.js中的demuxer，如果将[4908行](https://github.com/liqi0816/bilitwin/blob/master/biliTwin.user.js#L4908)和[4931行](https://github.com/liqi0816/bilitwin/blob/master/biliTwin.user.js#L4931)注释掉，MKV打包功能将只包括音频。但由于以flv为源，视频数据多，所以不推荐。*

**Comment by knightReigh** [comment]
对不起对不起，403的问题不是您这个脚本。因为今天测试了几个不同的b站下载工具，所以不小心弄混了。我想要反馈的是另外一个java写的脚本。您的脚本非常好用T T。

我猜想interface也是一个api，需要输入正确的header和key才可以访问。但妄想是不是可以分离出mp4/flv的直连地址。

关于直接视频中提取音频，因为我找到了这个网站：https://video-download.co/。 输入视频地址提供音频下载非常快，差不多10秒就生成音频文件，所以我认为应该是有办法直接读取音频的。。不过它没有api，不能批量实现下载。。

非常不好意思，打扰您了
