### ISSUE TITLE
是否有机会增加播放清单功能

### ISSUE THREAD

**Issue by Wcw5504** [liqi0816/bilitwin#7]
因为目前用A卡，假使可行的话都用MPC配FM补帧
暂时没有缓存到本地播放的需求，只希望用本机播放器时，分段flv可以一次播完
虽然自己在本地新建一个m3u，把连结粘贴过去，或者一个个加进播放佇列也能达成相同效果
但每个视频都要手动操作一次实在有点麻烦

**Comment by liqi0816** [comment]
已经增加了m3u8功能。欢迎阁下试试m3u8分支：https://github.com/liqi0816/bilitwin/raw/export-m3u8/biliTwin.user.js

这项功能太过小众，而且referrer设置项`EXTVLCOPT:http-referrer`仅被部分播放器支持，所以并*不*一定会加到正式版中。

**Comment by Wcw5504** [comment]
尝试后可用，感谢作者
