### ISSUE TITLE
UI改进建议

### ISSUE THREAD

**Issue by changhexiong** [liqi0816/bilitwin#8]
视频标题下面的那一行蓝字（超清FLV 原生MP4 弹幕ASS）感觉和整个页面格格不入……能不能取消或者在设置里隐藏？因为这几个功能在右键菜单里都有。

**Comment by liqi0816** [comment]
取消的话，Edge会坏掉，因为它不支持右键菜单。

可以加设置，但因为这不影响使用，看心情

> 快了~

**Comment by liqi0816** [comment]
多谢阁下反馈。现在提供了新的选项，可以隐藏标题链接。欢迎阁下试试开发版本
https://github.com/liqi0816/bilitwin/raw/develop/biliTwin.user.js

如果可用，将在两天后释出。
