### ISSUE TITLE
求问 不知道怎么使用

### ISSUE THREAD

**Issue by pannacea** [liqi0816/bilitwin#9]
安装过了脚本 但是打开动画页面还是没有 但是其他自上传的视频可以下载这是为什么

**Comment by pannacea** [comment]
这样的就是打开番剧 不能下载 但是其他的脚本就会有响应

**Comment by liqi0816** [comment]
……哪一个页面？哪一个浏览器？

**Comment by pannacea** [comment]
浏览器用的极速浏览器 页面的话就是动画播放页面

**Comment by liqi0816** [comment]
……仅靠完整的网址和完整的浏览器名称，并不能精准定位阁下。可以给出完整的信息吗？哪家出的极速浏览器？哪个动画的播放页面？

**Comment by pannacea** [comment]
360极速……   动画的话你随便点一个都是一样的，如果你要具体网址的话，我暂时还没有用电脑，管一阵子给你发

**Comment by pannacea** [comment]
问题就是360极速浏览器 这样说吧 除了动画页面不能下载 其他的都可以下

**Comment by liqi0816** [comment]
多谢阁下反馈。在上一次更新中，脚本支持了新番剧页面，但发布国产浏览器特供版时，只增加了逻辑，忘记加上网址匹配规则了……欢迎阁下试试修正版本：https://github.com/liqi0816/bilitwin/raw/develop/biliTwinBabelCompiled.user.js

如果可用，将立即发布到master。

**Comment by pannacea** [comment]
可以用了 感谢

**Comment by pannacea** [comment]
现在亲测下载 可以用 但晒  下载后的路径在哪里= =

**Comment by liqi0816** [comment]
mkv是个比较新的功能，遇到比较奇怪的视频编码(合作方，无二压之类的)会扑街，先用flv+ass凑合一下吧

**Comment by pannacea** [comment]
不不不 这个不是重点  就是生成flv文件 点击全部缓存+合并后 （这个时段下载速度很快）完成后 有一个保存flv的点击 然后会生成一个下载 下载地址无法使用啊  看了下链接 我试着删除前面的blob: 但是还是无法下载

**Comment by liqi0816** [comment]
- `blob:`不能删。脚本在本地合并flv。

  > BLOB (binary large object)，二进制大对象，是一个可以存储二进制文件的容器。

- 360极速浏览器给人一种比Chrome节约内存，适合低配机器的“印象”，有它的代价。它会清理掉网页中它*认为*不重要的东西——合并flv那么大一个目标当然不会被放过。解决办法也很简单，刷新就好了。脚本支持断点续传，可以重新合并。

**Comment by pannacea** [comment]
意思是 反复重新下载 问题是全部缓存后 下不动- -

**Comment by liqi0816** [comment]
意思是，刷新，然后重新合并。不用重新下载。

**Comment by pannacea** [comment]
将才试过了  还是一样的普通视频可以 动画用合并flv后无法下载

**Comment by liqi0816** [comment]
……360浏览器的版本是？能把任务管理器的内存占用截图看看吗？

**Comment by pannacea** [comment]
没事= =下载了一个flv合并器不影响  问题就是你想要下载直接合并的不行 分段可以保存 然后手动合并就好了
